name = "twisted"
main = "index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

# Workers configuration
workers_dev = true

# Observability - Logs
[observability]

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
