const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const read = (file) => fs.readFileSync(path.resolve(__dirname, '..', file), 'utf8');

test('CI verifies tests, types, generated bindings, and OpenNext before a manual production deploy', () => {
  const workflow = read('.github/workflows/deploy.yml');
  for (const step of ['npm test', 'npm run typecheck', 'npm run cf-typecheck', 'npm run build:opennext']) assert.match(workflow, new RegExp(step.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.ok(workflow.indexOf('npm test') < workflow.indexOf('npm run typecheck'));
  assert.ok(workflow.indexOf('npm run typecheck') < workflow.indexOf('npm run build:opennext'));
  assert.match(workflow, /if: github\.event_name == 'workflow_dispatch'/);
  assert.match(workflow, /environment:\s*production/);
  assert.equal((workflow.match(/NEXT_PUBLIC_TURNSTILE_SITE_KEY:\s*\$\{\{ vars\.NEXT_PUBLIC_TURNSTILE_SITE_KEY \}\}/g) ?? []).length, 2);
  assert.equal((workflow.match(/node-version:\s*'22'/g) ?? []).length, 2);
});

test('package test command is cross-platform and generated binding check is explicit', () => {
  const pkg = JSON.parse(read('package.json'));
  const lock = JSON.parse(read('package-lock.json'));
  assert.equal(pkg.scripts.test, 'node scripts/run-tests.cjs');
  assert.equal(pkg.scripts['cf-typecheck'], 'node scripts/check-cloudflare-types.cjs --check');
	assert.equal(pkg.engines.node, '22.x');
	assert.match(read('scripts/check-cloudflare-types.cjs'), /'types'/);
  assert.equal(pkg.devDependencies.wrangler, lock.packages['node_modules/wrangler'].version);
	assert.match(read('scripts/cloudflare-types-model.cjs'), /mkdtempSync/);
  assert.match(read('scripts/check-cloudflare-types.cjs'), /if \(checkOnly\)[\s\S]*?fs\.readFileSync\(target/);
  assert.match(read('scripts/check-cloudflare-types.cjs'), /else \{\s*fs\.writeFileSync\(target/);
	assert.doesNotMatch(pkg.scripts.test, /\*/);
	assert.doesNotMatch(read('scripts/check-cloudflare-types.cjs'), /process\.exit\(/);
	assert.match(read('cloudflare-env.d.ts').split(/\r?\n/u)[1], /^\/\/ Generated by Wrangler \(configuration hash: [0-9a-f]+\)$/u);
});

test('deployment guide documents lifecycle and manual publication gates without declaring readiness', () => {
  const guide = read('docs/deployment-guide.md');
  for (const text of ['order-intents/', 'order-uploads/', 'order-assets/', 'order-manifests/', 'WAF', 'Turnstile', 'Images']) assert.match(guide, new RegExp(text, 'i'));
  assert.doesNotMatch(guide, /Ready for Deployment/i);
});

test('README and original order documents describe only the authoritative deployment and asset contracts', () => {
  const readme = read('README.md');
  assert.match(readme, /workflow_dispatch/);
  assert.match(readme, /protected[^\n]*production environment/i);
  assert.match(readme, /wrangler\.jsonc/);
  assert.doesNotMatch(readme, /automatically[^\n]*deploy/i);
  assert.doesNotMatch(readme, /wrangler\.toml/);
  assert.match(readme, /Node\.js 22/);
  for (const binding of ['ASSETS', 'IMAGES', 'DB', 'ORDER_ASSETS', 'ORDER_INTENT_RATE_LIMITER', 'ORDER_UPLOAD_RATE_LIMITER', 'ORDER_CHECKOUT_RATE_LIMITER']) {
    assert.match(readme, new RegExp(`\\b${binding}\\b`));
  }
  assert.doesNotMatch(readme, /Planned Bindings[\s\S]*?\*\*(?:D1 Database|R2 Object Storage)\*\*/i);

  for (const file of [
    'docs/superpowers/specs/2026-08-02-custom-order-assistant-design.md',
    'docs/superpowers/plans/2026-08-02-custom-order-assistant.md',
  ]) {
    const source = read(file);
    assert.doesNotMatch(source, /image\/(?:webp|heic)|WebP\/HEIC|orders\//i);
    assert.doesNotMatch(source, /1,?000.character[^\n]*note/i);
    assert.match(source, /500.character[^\n]*note/i);
    assert.match(source, /order-manifests\//);
    assert.match(source, /customization[^\n]*2,?000/i);
    assert.match(source, /notes?[^\n]*300/i);
    assert.match(source, /order-assets\/<checkout-attempt-id>\/<upload-uuid>\.jpg/i);
  }
});

test('popup route uses the generated Cloudflare DB binding without process environment casts', () => {
  const route = read('src/app/api/popup/route.ts');
  assert.match(route, /getCloudflareContext\(\)\.env\.DB/);
  assert.doesNotMatch(route, /process\.env|as unknown as/);
});
