const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');

const model = require('./cloudflare-types-model.cjs');

test('generated binding banners are identical after Windows and Linux checkout relocation', () => {
  const hash = '314a23b376b8bb7c0a3b247924c6d3d2';
  const windows = `// Generated by Wrangler by running \`wrangler types --config=C:\\Users\\conni\\repo\\wrangler.jsonc --env-interface=CloudflareEnv C:\\Temp\\types\\cloudflare-env.d.ts\` (hash: ${hash})\ninterface CloudflareEnv {}`;
  const linux = `// Generated by Wrangler by running \`wrangler types --config=/home/runner/work/repo/wrangler.jsonc --env-interface=CloudflareEnv /tmp/types/cloudflare-env.d.ts\` (hash: ${hash})\ninterface CloudflareEnv {}`;
  const expected = `// Generated by Wrangler (configuration hash: ${hash})\ninterface CloudflareEnv {}`;

  assert.equal(model.normalizeGeneratedTypes(windows), expected);
  assert.equal(model.normalizeGeneratedTypes(linux), expected);
});

test('temporary generated bindings are removed after both success and failure callbacks', () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'tcl-types-model-test-'));
  try {
    for (const callback of [() => 'ok', () => { throw new Error('generation failed'); }]) {
      const before = new Set(fs.readdirSync(parent));
      try { model.withTemporaryDirectory(parent, callback); } catch {}
      assert.deepEqual(new Set(fs.readdirSync(parent)), before);
    }
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});
